apiVersion: v1
kind: ServiceAccount
metadata:
  name: eureka-server-sa
  namespace: microservices-pro
  labels:
    app.kubernetes.io/part-of: microservices-pro-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-server-sa
  namespace: microservices-pro
  labels:
    app.kubernetes.io/part-of: microservices-pro-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: microservices-pro
  labels:
    app.kubernetes.io/part-of: microservices-pro-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service-sa
  namespace: microservices-pro
  labels:
    app.kubernetes.io/part-of: microservices-pro-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: microservices-pro
  labels:
    app.kubernetes.io/part-of: microservices-pro-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service-sa
  namespace: microservices-pro
  labels:
    app.kubernetes.io/part-of: microservices-pro-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service-sa
  namespace: microservices-pro
  labels:
    app.kubernetes.io/part-of: microservices-pro-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  namespace: microservices-pro
  labels:
    app.kubernetes.io/part-of: microservices-pro-platform
