apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: microservices-pro
  labels:
    app.kubernetes.io/part-of: microservices-pro-platform
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/microservices_pro"
  SPRING_DATASOURCE_USERNAME: "postgres"
  MANAGEMENT_HEALTH_PROBES_ENABLED: "true"
  PAYMENT_FAILURE_RATE: "0.0"
  PAYMENT_DELAY_MS: "0"
