package com.microservices.pro.inventoryservice;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import au.com.dius.pact.provider.spring.junit5.PactVerificationSpringProvider;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.test.context.TestPropertySource;

/**
 * InventoryServicePactVerificationTest — Session 11, Lab 9B, Task 2.
 *
 * Provider-side verification: inventory-service reads the pact.json file
 * generated by order-service's consumer test and verifies that its
 * /api/v1/inventory/check endpoint returns a response that satisfies
 * every expectation in the contract.
 *
 * @PactFolder("../order-service/target/pacts") — reads the pact.json
 * generated by order-service. This path is relative to the inventory-service
 * module root and assumes both services are siblings in the repo root.
 * Run order-service's Pact consumer test FIRST:
 *   mvn test -pl services/order-service -Dtest=OrderServiceInventoryContractTest
 * Then run this test:
 *   mvn test -pl services/inventory-service -Dtest=InventoryServicePactVerificationTest
 *
 * Teaching point (Session 11 docx, "rename bug"):
 *   If InventoryService renames 'available' → 'inStock', THIS test fails with:
 *   "Expected field 'available' but was missing in response body"
 *   The consumer's unit tests keep passing. The contract catches the breakage
 *   before it reaches production.
 *
 * @State setup: each @State method puts the in-memory stock into the
 * exact state the consumer's @Pact "given(...)" clause describes.
 * Uses InventoryService.resetForTesting() — a package-private test helper
 * that should NOT be used in production code.
 */
@Provider("inventory-service")
@PactFolder("../order-service/target/pacts")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@TestPropertySource(properties = {
        "eureka.client.enabled=false",
        "spring.cloud.config.enabled=false",
        "spring.config.import=",
        "spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration"
})
class InventoryServicePactVerificationTest {

    @LocalServerPort
    private int port;

    @Autowired
    private InventoryService inventoryService;

    @MockBean
    private KafkaTemplate<String, Object> kafkaTemplate;

    @BeforeEach
    void setUp(PactVerificationContext context) {
        context.setTarget(new HttpTestTarget("localhost", port));
    }

    @TestTemplate
    @ExtendWith(PactVerificationSpringProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context) {
        context.verifyInteraction();
    }

    @State("PROD-001 has 100 units in stock")
    void setupProd001FullStock() {
        inventoryService.resetForTesting("PROD-001", 100, 0);
    }

    @State("PROD-003 is out of stock")
    void setupProd003OutOfStock() {
        inventoryService.resetForTesting("PROD-003", 0, 0);
    }
}
