# api-gateway.yml
# Served by Config Server to API Gateway at startup (Session 2).

app:
  source: "config-server"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
