# inventory-service.yml
# Served by Config Server to Inventory Service at startup.

app:
  source: "config-server"

spring:
  kafka:
    listener:
      observation-enabled: true
    template:
      observation-enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
